//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calculator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string ClearAllSign {
            get {
                return ResourceManager.GetString("ClearAllSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÷.
        /// </summary>
        public static string DivisionSign {
            get {
                return ResourceManager.GetString("DivisionSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        public static string Dot {
            get {
                return ResourceManager.GetString("Dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        public static string EqualSign {
            get {
                return ResourceManager.GetString("EqualSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x².
        /// </summary>
        public static string ExponentSign {
            get {
                return ResourceManager.GetString("ExponentSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ∞.
        /// </summary>
        public static string Infinity {
            get {
                return ResourceManager.GetString("Infinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string MinusSign {
            get {
                return ResourceManager.GetString("MinusSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ×.
        /// </summary>
        public static string MultiplicationSign {
            get {
                return ResourceManager.GetString("MultiplicationSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string Number0 {
            get {
                return ResourceManager.GetString("Number0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string Number1 {
            get {
                return ResourceManager.GetString("Number1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string Number2 {
            get {
                return ResourceManager.GetString("Number2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string Number3 {
            get {
                return ResourceManager.GetString("Number3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string Number4 {
            get {
                return ResourceManager.GetString("Number4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string Number5 {
            get {
                return ResourceManager.GetString("Number5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string Number6 {
            get {
                return ResourceManager.GetString("Number6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string Number7 {
            get {
                return ResourceManager.GetString("Number7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        public static string Number8 {
            get {
                return ResourceManager.GetString("Number8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        public static string Number9 {
            get {
                return ResourceManager.GetString("Number9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ±.
        /// </summary>
        public static string PlusMinusSign {
            get {
                return ResourceManager.GetString("PlusMinusSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        public static string PlusSign {
            get {
                return ResourceManager.GetString("PlusSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Undefined.
        /// </summary>
        public static string ResultUndefined {
            get {
                return ResourceManager.GetString("ResultUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to √.
        /// </summary>
        public static string RootSign {
            get {
                return ResourceManager.GetString("RootSign", resourceCulture);
            }
        }
    }
}
